refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} | {h({l}):5.5} | {M} - {m}{n}"
  file:
    kind: rolling_file
    path: "logs/taiyaki-maker.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} | {h({l}):5.5} | {M} - {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: delete

root:
  level: warn
  appenders:
    - stdout
    - file

loggers:
  taiyaki_maker:
    level: info